default:

  ckeditor:
    config:
      toolbar:
        - ['Maximize']
        - ['Format', 'Bold', 'Italic','Strike','Blockquote', '-', 'NumberedList', 'BulletedList', '-', 'Link', 'Unlink']
        - ['PasteText','PasteFromWord']
        - ['Undo','Redo']
        - ['Image','HorizontalRule','SpecialChar']
      resize_enabled:     false
      extraPlugins:       diem
      customConfig:       ''
      baseFloatZIndex:    20000000        # set to a higher value defined for jquery ui dialogs, see dmCoreEditCtrl.js